# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      # Make sure you put workflow kit action on top of all the steps 
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: 073e8995-1c58-4540-88d4-44b74cc76e47

      # Make sure you put test kit action after your test execution step 
      - name: Analyze Test and/or Coverage Results
        uses: thundra-io/foresight-test-kit-action@v1
        with:
          api_key: 073e8995-1c58-4540-88d4-44b74cc76e47
